##################################################################
# Panilla Bukkit Configuration
#
# Resource page: https://www.spigotmc.org/resources/65694/
# Source code: https://github.com/Ruinscraft/Panilla
# Issues and help https://github.com/Ruinscraft/Panilla/issues
##################################################################

# The language option below currently does nothing.
language: en

# Logging options
logging:
  console: false
  chat: false

# Strictness of how much you wish to enforce
#   lenient - Only prevent game-breaking things or crashes
#   average - Prevent most abusive things (recommended)
#   strict  - Prevent anything non-vanilla
strictness: average

# This prevents users from creating high resolution skulls with
# a Minecraft Education account (or possibly other methods)
#
# See this paste for more information: https://paste.ubuntu.com/p/SSGg6szMc4/
prevent-minecraft-education-skulls: false

# This prevents FAWE brush NBT on items. It stops users from giving
# out FAWE brush items which may trick others into accidentally WorldEdit'ing
prevent-fawe-brush-nbt: false

# When checking packets, by default, Panilla will check any inventory (player, chest, etc...)
# Setting this to true will make Panilla only check player inventories

# This can help with ensuring custom GUI's in plugins don't get flagged
# This may also marginally improve performance
ignore-non-player-inventories: false

# When true, this will prevent any BlockEntityTag NBT regardless of strictness
# This will break things like ShulkerBoxes
# Generally not recommended
no-block-entity-tag: false

# Whitelist NBT tags from being checked
# Keep in mind some NBT tags vary between Minecraft versions
#     (eg: ench on 1.12 vs Enchantments on 1.13)
nbt-whitelist:
#  - Enchantments

# Prevent Panilla from checking NBT in certain worlds
# Effectively sets the world to the lenient strictness (to prevent crash exploits)
# Case sensitive!
disabled-worlds:
#  - world_nether
#  - some_other_world_name

# Override Minecraft's max enchantment levels
# Useful if you want to manually set a max enchantment level for specific enchantments
# You must use either normal or strict mode for this to work
# Find a list of Minecraft enchantment names here: https://www.digminecraft.com/lists/enchantment_list_pc.php
max-enchantment-levels:
  override-minecraft-max-enchantment-levels: false
  overrides:
    sharpness: 15
    protection: 10
    feather_falling: 10

# This is to prevent crash items which have an excessive
# amount of NBT keys.
#
# If you have plugins which use an excessive amount of
# custom NBT keys, then you can raise it as high as you like.
#
# Generally, you should never have to touch this.
max-non-minecraft-nbt-keys: 16
